---
- project:
    check:
      jobs:
        - pre-commit
        - dist2src-tests
    gate:
      jobs:
        - pre-commit
- job:
    # job names are global, this should be unique
    name: dist2src-tests
    parent: base
    attempts: 1
    description: Run tests
    extra-vars:
      ansible_python_interpreter: /usr/bin/python3
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-32
    run: zuul-tests.yaml
