---
- project:
    check:
      jobs:
        - pre-commit
        - dist2src-tests
    gate:
      jobs:
        - pre-commit

- job:
    # job names are global, this should be unique
    name: dist2src-tests
    parent: base
    description: Run tests
    run: files/zuul-tests.yaml
