---
- project:
    check:
      jobs:
        - pre-commit
        - dist2src-tests
        - dist2src-deployment-tests
    gate:
      jobs:
        - pre-commit

- job:
    # job names are global, this should be unique
    name: dist2src-tests
    parent: base
    description: Run tests
    run: files/zuul-tests.yaml
    timeout: 3600 # 60 minutes

- job:
    name: dist2src-deployment-tests
    parent: oc-cluster-up
    description: Deploy and check
    extra-vars:
      deployment: dev
    pre-run:
      - files/zuul-build-image.yml
      - files/zuul-generate-secrets.yml
      - files/zuul-deploy.yml
    run: files/zuul-check.yml
