# To deploy to local cluster, just set the api_key and run
# DEPLOYMENT=local make deploy

---
project: myproject

host: https://127.0.0.1:8443

validate_certs: no

push_dev_images: true

api_key: ""
