# To deploy to local cluster, just set the api_key and run
# DEPLOYMENT=local make deploy

---
project: myproject

host: https://127.0.0.1:8443

validate_certs: no

push_dev_images: true

auto_import_images: false

api_key: ""

dist_git_url: https://git.centos.org
src_git_url: https://git.stg.centos.org

branches_watched:
  - c8s
  - c8
  - c8s-stream-rhel

dist_git_namespace: rpms

src_git_namespace: source-git
