---
- name: Install dependencies for dist2src
  hosts: all
  tasks:
    - name: Install as many (setup.cfg) deps from RPM as possible
      dnf:
        name:
          - rpm-build
          - python3-GitPython
          - python3-celery
          - python3-redis
          - python3-lazy-object-proxy
          - python3-timeout-decorator
          - packit
        state: latest
        enablerepo: powertools
    - name: Install tools required by %prep section of some packages
      dnf:
        name:
          - bison
          - flex
          - make
          - autoconf
          - automake
          - gettext-devel
          - sscg
          - libtool
          - dos2unix
          - perl-devel
          - rubygems
          # httpd
          - xmlto
          # kernel needs pathfix.py
          - python3-devel
          # pandoc
          - ghc-rpm-macros
        state: latest
    - name: Install gtk-doc
      shell: dnf --enablerepo=powertools --setopt=powertools.module_hotfixes=true install -y javapackages-local gtk-doc
      args:
        warn: no
    - name: Install python3-ipython to speed up ipdb install
      dnf:
        name:
          - python3-ipython
        state: latest
    - name: Pip install tools for debugging, tests
      pip:
        name:
          - ipdb
          - pytest
          - flexmock
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip3 check
