---
- name: Install dist2src worker
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Copy run_worker.sh
      copy:
        src: run_worker.sh
        dest: /usr/bin/run_worker.sh
        mode: 0777
    - name: Create packit home dir
      file:
        state: directory
        path: "{{ home_path }}"
        mode: 0776
    - name: Copy gitconfig
      copy:
        src: gitconfig
        dest: "{{ home_path }}/.gitconfig"
