# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Create dummy secrets
  hosts: all
  vars:
    project_dir: "{{ playbook_dir }}/.."
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
    secrets_dir: "{{ project_dir }}/deployment/roles/deploy/files/secrets/{{ deployment }}"
  tasks:
    - file:
        path: "{{ secrets_dir }}"
        state: directory
    - file:
        path: "{{ secrets_dir }}/ssh"
        state: directory
    - file:
        path: "{{ secrets_dir }}/{{ item }}"
        state: touch
      loop:
        - sentry_dsn
        - centos.cert
        - centos-server-ca.cert
        - dist-git-token
        - src-git-token
        - ssh/id_rsa
        - ssh/id_rsa.pub
