# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Deploy aggregating pushgateway and nginx to reverse proxy the pushgateway
  k8s:
    namespace: "{{ project }}"
    resource_definition: "{{ item }}"
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    validate_certs: "{{ validate_certs }}"
  with_file:
    - pushgateway-dc.yml
    - pushgateway-service.yml
    - nginx-dc.yml
    - nginx-service.yml
    - nginx-route.yml
  tags:
    - pushgateway
