# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- fail: msg="DEPLOYMENT is not set"
  when: deployment|length == 0
- include_vars: "{{ deployment }}.yml"

- include_tasks: ./check-api-token.yml
- include_tasks: ./push-dev-images.yml
  when: push_dev_images
- include_tasks: ./deploy-secrets.yml
- include_tasks: ./deploy-configmap.yml
- include_tasks: ./deploy-redis.yml
- include_tasks: ./deploy-worker.yml
- include_tasks: ./deploy-centosmsg.yml
- include_tasks: ./wait-for-pods.yml
